<?php
/**
 * @file
 * Code for the Red Door Events feature.
 */

include_once 'rd_events.features.inc';

function rd_events_form_event_node_form_alter(&$form, &$form_state) {
  if(!drupal_add_library('rd_events', 'jquery-timepicker')) {
    dsm('shit');
  }
  drupal_add_js(
    drupal_get_path('module', 'rd_events') . '/rd_events.js',
    array('type' => 'file', 'group' => JS_THEME)
  );
}

function rd_events_library() {
  $path = libraries_get_path('jquery-timepicker');
  $libraries['rd_events'] = array(
    'title' => 'jQuery Timepicker',
    'website' => 'https://github.com/jonthornton/jquery-timepicker',
    'version' => '1.0',
    'js' => array(
      "$path/jquery-timepicker.min.js" => array()
    ),
    'css' => array(
      "$path/jquery-timepicker.css" => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );
  return $libraries;
}
